GET http://localhost:8000/interventions

###
GET  http://localhost:8000/interventions/5e2eeede20c2ad0ca8d702b5

###
DELETE http://localhost:8000/interventions/5e2f1b1e1ce5611fb08b9cf3


###
POST http://localhost:8000/interventions
Content-Type: application/json

{  
  "createdBy": "7",
  "tittle": "Bad Roads",
  "type": "red flag",
  "location": "Kampala",
  "status": "Draft",
  "comment": "The water was too much."
}

###


PATCH   http://localhost:8000/interventions/5e316ae2d677b415648c6d4d
Content-Type: application/json 

{  "createdBy":"7",
   "tittle": "Bad Roads",
   "type": "intervention",
   "location": "Masaka",
   "status": "draft",
   "comment": "The water was to much."
}
###
POST  http://localhost:8000/auth/signup
Content-Type: application/json

{  "firstName": "Lugonvu",
   "lastName": "Mayimuna",
   "email":"munalugou@gmail.com",
   "phoneNumber": "0700255935",
   "userName": "muna3lujonvu",
   "password": "122156mm "
}
###
POST  http://localhost:8000/auth/signin
Content-Type: application/json

{ 
   "email":"munalugonvu@gmail.com",
   "password":"122156mm"
}

###
PUT   http://localhost:8000/auth/update-user/5e330d8642d0b108b8ed3525
Content-Type: application/json

{
    "firstName": "mona"
}




###
GET http://localhost:8000/auth
###
DELETE http://localhost:8000/auth/delete-user/5e330d8642d0b108b8ed3525