GET http://localhost:8000/interventions

###
GET  http://localhost:8000/interventions/5e3054ea08359e0a543553d7

###
DELETE http://localhost:8000/interventions/5e3056fd08359e0a543553d8


###
POST http://localhost:8000/interventions
Content-Type: application/json

{  
  "createdBy": "7",
  "tittle": "Bad Roads",
  "type": "redflag",
  "location": "Kitugum",
  "status": "Draft",
  "comment": "The water was too much."
}

###


PATCH   http://localhost:8000/interventions/5e316ae2d677b415648c6d4d
Content-Type: application/json 

{  "createdBy":"7",
   "tittle": "Bad Roads",
   "type": "intervention",
   "location": "Masaka",
   "status": "draft",
   "comment": "The water was to much."
}
###
POST  http://localhost:8000/auth/signup
Content-Type: application/json

{  "firstName": "Lungnvu",
   "lastName": "Mayimjnvhuna",
   "email":"muna@gmail.com",
   "phoneNumber": "0700825ngc5935",
   "userName": "mincuk2121",
   "password": "12215hfgh6"
}
###
POST  http://localhost:8000/auth/signin
Content-Type: application/json

{ 
   "email":"munalngujgfoku@gmail.com",
   "password":"12215hfgh6hkmhjfhjm "
}

###
PUT   http://localhost:8000/auth/update-user/5e330d8642d0b108b8ed3525
Content-Type: application/json

{
    "firstName": "lucky"
}




###
GET http://localhost:8000/auth
###
DELETE http://localhost:8000/auth/delete-user/m5e330d8642d0b108b8ed3525